version: "3.9"

services:
  web:
    image: nginx:stable-alpine
    container_name: novel-site-web
    ports:
      - "8080:80"
    volumes:
      # public -> /usr/share/nginx/html
      - ./public:/usr/share/nginx/html:ro
      # 自前の設定
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
